parameters:
    # proxy to use, f.ex. socks5://127.0.0.1:9999
    glooby.http.proxy:      ~

    # path to where a file can be used, containing the above information.
    # If glooby.http.proxyfile is set it will override the path.
    glooby.http.proxyfile:  ~

    # default timeout to use in secounds
    glooby.http.timeout:  ~

services:
    glooby.http.client_factory:
        class: Glooby\HttpClientBundle\Http\HttpClientFactory
        calls:
            - [ setLogger,            [ '@logger' ]]
            - [ setSettingsManager,   [ '@glooby.http.settings' ]]

    glooby.http.soap_client_factory:
        class: Glooby\HttpClientBundle\Soap\SoapClientFactory
        calls:
            - [ setLogger,            [ '@logger' ]]
            - [ setSettingsManager,   [ '@glooby.http.settings' ]]

    glooby.http.proxy_parser:
        class: Glooby\HttpClientBundle\Proxy\ProxyParser

    glooby.http.settings:
        class: Glooby\HttpClientBundle\HttpSettingsManager
        calls:
            - [setProxyParser,       ['@glooby.http.proxy_parser']]
            - [setProxy,             ['%glooby.http.proxy%']]
            - [setProxyFile,         ['%glooby.http.proxyfile%']]
            - [setTimeout,           ['%glooby.http.timeout%']]

    glooby.http.client:
        class: Glooby\HttpClientBundle\Http\HttpClient
        calls:
            - [setHttpClientFactory, ['@glooby.http.client_factory']]
            - [setLogger, ['@logger']]
